# Generated by Django 2.0.6 on 2020-04-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='id',
        ),
        migrations.AlterField(
            model_name='ipo',
            name='content',
            field=models.TextField(default='', verbose_name='募集资金的运用'),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='content2',
            field=models.TextField(default='', verbose_name='股权分配'),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='stock_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='股票ID'),
        ),
    ]
