# Generated by Django 2.0.6 on 2020-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200422_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='ipo_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
