# Generated by Django 2.0.6 on 2020-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200422_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='content',
            field=models.TextField(default=' ', verbose_name='募集资金的运用'),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='content2',
            field=models.TextField(default=' ', verbose_name='股权分配'),
        ),
    ]
