# Generated by Django 2.0.6 on 2020-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200422_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='stock_id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False, verbose_name='股票ID'),
        ),
    ]
