# Generated by Django 2.0.6 on 2020-04-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Euser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Euser',
            },
        ),
    ]
