# Generated by Django 2.0.6 on 2020-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='euser',
            name='address',
            field=models.CharField(default='', max_length=45),
        ),
    ]
