# Generated by Django 2.0.6 on 2020-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_euser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='password',
            field=models.CharField(max_length=45),
        ),
    ]
